version: "3.8"

services:
  # PostgreSQL 数据库
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: yixin
      POSTGRES_USER: yixin
      POSTGRES_PASSWORD: yixin
    ports:
      - "5433:5432" # 使用5433端口避免冲突
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yixin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI 应用
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://yixin:yixin@db:5432/yixin
      - MIGRATE_URL=postgresql+psycopg://yixin:yixin@db:5432/yixin
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
